package de.deftk.openww.api.model

import de.deftk.openww.api.model.Permission.*
import de.deftk.openww.api.model.SupportLevel.*

enum class Feature(val supportLevel: SupportLevel, vararg possiblePermissions: Permission) {
    STATISTICS(NOT_SUPPORTED, SYSADMIN),

    ADMINISTRATION_GROUP(NOT_SUPPORTED, ADMIN_READ, ADMIN_WRITE, ADMIN_ADMIN),
    ADMINISTRATION_USER(NOT_SUPPORTED, ADMIN_READ, ADMIN_WRITE, ADMIN_ADMIN),
    ADMINISTRATION_ROOT(NOT_SUPPORTED, ADMIN_READ, ADMIN_WRITE, ADMIN_ADMIN),

    MESSENGER(STABLE, MESSENGER_READ, MESSENGER_WRITE, MESSENGER_ADMIN),
    MAILBOX(STABLE, MAILBOX_READ, MAILBOX_WRITE, MAILBOX_ADMIN),
    MEMBERS(STABLE, MEMBERS_READ, MEMBERS_WRITE, MEMBERS_ADMIN),
    ADDRESSES(STABLE, ADDRESSES_READ, ADDRESSES_WRITE, ADDRESSES_ADMIN),
    CALENDAR(STABLE, CALENDAR_READ, CALENDAR_WRITE, CALENDAR_ADMIN),
    NOTES(STABLE, NOTES_READ, NOTES_WRITE, NOTES_ADMIN),
    BOARD(STABLE, BOARD_READ, BOARD_WRITE, BOARD_ADMIN),
    BOARD_PUPIL(STABLE, BOARD_PUPIL_READ, BOARD_PUPIL_WRITE, BOARD_PUPIL_ADMIN),
    BOARD_TEACHER(STABLE, BOARD_TEACHER_READ, BOARD_TEACHER_WRITE, BOARD_TEACHER_ADMIN),
    TASKS(STABLE, TASKS_READ, TASKS_WRITE, TASKS_ADMIN),
    BOOKS(NOT_SUPPORTED, BOOKS_READ, BOOKS_WRITE, BOOKS_ADMIN),
    BOOKMARKS(NOT_SUPPORTED, BOOKMARKS_READ, BOOKMARKS_WRITE , BOOKMARKS_ADMIN),
    COURSELETS(UNFINISHED, COURSELETS_READ, COURSELETS_WRITE, COURSELETS_ADMIN),
    FORUM(STABLE, FORUM_READ, FORUM_WRITE, FORUM_ADMIN),
    WIKI(STABLE, WIKI_READ, WIKI_WRITE, WIKI_ADMIN),
    RESOURCEMANAGEMENT(NOT_SUPPORTED, RESOURCEMANAGEMENT_READ, RESOURCEMANAGEMENT_WRITE, RESOURCEMANAGEMENT_ADMIN),
    FILES(STABLE, FILES_READ, FILES_WRITE, FILES_ADMIN),
    CHAT(NOT_SUPPORTED, CHAT_READ, CHAT_WRITE, CHAT_ADMIN),
    BLOG(NOT_SUPPORTED, BLOG_READ, BLOG_WRITE, BLOG_ADMIN),
    SHOWCASE(NOT_SUPPORTED, SHOWCASE_READ, SHOWCASE_WRITE, SHOWCASE_ADMIN),
    WEBSITE(NOT_SUPPORTED, WEBSITE_READ, WEBSITE_WRITE, WEBSITE_ADMIN),
    WS_GEN(NOT_SUPPORTED, WS_GEN_READ, WS_GEN_WRITE, WS_GEN_ADMIN),
    POLL(NOT_SUPPORTED, POLL_READ, POLL_WRITE, POLL_ADMIN),
    LEARNING_PLAN(NOT_SUPPORTED, LEARNING_PLAN_READ, LEARNING_PLAN_WRITE, LEARNING_PLAN_ADMIN),
    TIMETABLE(NOT_SUPPORTED, TIMETABLE_READ, TIMETABLE_WRITE, TIMETABLE_ADMIN),
    MAILING_LIST(NOT_SUPPORTED, MAILING_LISTS_READ, MAILING_LISTS_WRITE, MAILING_LISTS_ADMIN),
    META(NOT_SUPPORTED, META_READ, META_WRITE, META_ADMIN),
    LEARNING_LOG(NOT_SUPPORTED, LEARNING_LOG_READ, LEARNING_LOG_WRITE, LEARNING_LOG_ADMIN),
    WALL(NOT_SUPPORTED, WALL_READ, WALL_WRITE, WALL_ADMIN),
    SUBSTITUTION_PLAN(NOT_SUPPORTED, SUBSTITUTION_PLAN_READ, SUBSTITUTION_PLAN_WRITE, SUBSTITUTION_PLAN_ADMIN),
    RESOURCE_MANAGEMENT(NOT_SUPPORTED, RESOURCE_MANAGEMENT_READ, RESOURCE_MANAGEMENT_WRITE, RESOURCE_MANAGEMENT_ADMIN),
    CONSULTATION_HOURS(NOT_SUPPORTED, CONSULTATION_HOURS_READ, CONSULTATION_HOURS_WRITE, CONSULTATION_HOURS_ADMIN),
    IMAGES(NOT_SUPPORTED, IMAGES_READ, IMAGES_WRITE, IMAGES_ADMIN),
    FORMS(NOT_SUPPORTED, FORMS_READ, FORMS_WRITE, FORMS_ADMIN),

    PROFILE(STABLE, PROFILE_READ, PROFILE_WRITE, PROFILE_ADMIN),

    SESSION_FILES(STABLE, SELF),
    LICENSES(NOT_SUPPORTED, SELF),
    MESSAGES(STABLE, SELF),
    TRUSTS(STABLE, SELF),
    SETTINGS(STABLE, SELF),
    PROXY(NOT_SUPPORTED, SELF),

    PASSWORD(NOT_SUPPORTED, Permission.PASSWORD),
    CLIENT(STABLE, Permission.CLIENT);

    val permissions: Array<out Permission> = possiblePermissions

    fun isAvailable(permissions: List<Permission?>): Boolean {
        this.permissions.forEach { permission ->
            if (permissions.contains(permission))
                return true
        }
        return false
    }

    companion object {
        fun getAvailableFeatures(permission: Permission): List<Feature> {
            return values().filter { it.permissions.contains(permission) }
        }
    }
}