package de.deftk.lonet.api.model

import java.io.Serializable

enum class Permission(val permission: String): Serializable {
    STATISTICS("sysadmin"),
    ADMINISTRATION_GROUP("admin"),
    ADMINISTRATION_GROUP_ADMIN("admin_admin"),
    ADMINISTRATION_USER("admin"),
    ADMINISTRATION_USER_ADMIN("admin_admin"),
    ADMINISTRATION_ROOT("admin"),
    ADMINISTRATION_ROOT_WRITE("admin_write"),
    MESSENGER("messenger"),
    MESSENGER_WRITE("messenger_write"),
    MAILBOX("mail"),
    MAILBOX_WRITE("mail_write"),
    MAILBOX_ADMIN("mail_admin"),
    MAILING_LISTS_ADMIN("mailing_lists_admin"),
    MEMBERS("members"),
    MEMBERS_WRITE("members_write"),
    MEMBERS_ADMIN("members_admin"),
    ADDRESSES("address"),
    ADDRESSES_WRITE("address_write"),
    ADDRESSES_ADMIN("address_admin"),
    CALENDAR("calendar"),
    CALENDAR_WRITE("calendar_write"),
    CALENDAR_ADMIN("calendar_admin"),
    CHAT("chat"),
    CHAT_WRITE("chat_write"),
    CHAT_ADMIN("chat_admin"),
    NOTES("notes"),
    NOTES_WRITE("notes_write"),
    BOOKS_WRITE("books_write"),
    BOOKMARKS("bookmarks"),
    BOOKMARKS_ADMIN("bookmarks_admin"),
    BOARD("board"),
    BOARD_WRITE("board_write"),
    BOARD_ADMIN("board_admin"),
    BOARD_TEACHER("board"),
    BOARD_TEACHER_WRITE("board_write"),
    BOARD_PUPIL("board_pupil"),
    BOARD_PUPIL_WRITE("board_pupil_write"),
    BOARD_PUPIL_ADMIN("board_pupil_admin"),
    TASKS("tasks"),
    TASKS_WRITE("tasks_write"),
    TASKS_ADMIN("tasks_admin"),
    COURSELETS("courselets"),
    COURSELETS_WRITE("courselets_write"),
    COURSELETS_ADMIN("courselets_admin"),
    FORUM("forum"),
    FORUM_WRITE("forum_write"),
    FORUM_ADMIN("forum_admin"),
    WIKI("wiki"),
    WIKI_ADMIN("wiki_admin"),
    RESOURCEMANAGEMENT("resourcemanagement"),
    RESOURCEMANAGEMENT_WRITE("resourcemanagement_write"),
    RESOURCEMANAGEMENT_ADMIN("resourcemanagement_admin"),
    FILES("files"),
    FILES_WRITE("files_write"),
    FILES_ADMIN("files_admin"),
    POLL("poll"),
    POLL_ADMIN("poll_admin"),
    TIMETABLE("timetable"),
    TIMETABLE_WRITE("timetable_write"),
    LEARNING_PLAN("learning_plan"),
    LEARNING_PLAN_ADMIN("learning_plan_admin"),
    WS_GEN("ws_gen"),
    WS_GEN_ADMIN("ws_gen_admin"),
    WEBSITE("website"),
    WEBSITE_ADMIN("website_admin"),
    SHOWCASE("showcase"),
    SHOWCASE_WRITE("showcase_write"),
    BLOG("blog"),
    BLOG_ADMIN("blog_admin"),
    CLIENT("client"),
    SESSION_FILES("self"),
    LICENSES("self"),
    PROFILE("profile"),
    MESSAGES("self"),
    SETTINGS("settings"),
    PROXY("self"),
    TRUSTS("self"),
    PASSWORD("password"),
    META("meta"),
    META_ADMIN("meta_admin"),
    UNKNOWN("");

    companion object {
        @JvmStatic
        fun getByName(name: String): List<Permission> {
            val list = values().filter { it.permission == name }
            return if (list.isEmpty()) {
                println("unknown permission: $name")
                listOf(UNKNOWN)
            } else list
        }
    }
}